print("Set")
print("Note: Set does not follow the order odf the elements and it is uniqie")
foods = {"Burger", "Pizza", "Chowmin", "Momo", "Thuppa", "Momo", "Burger"}
print(foods)
print("Data type of foods is", type(foods))
print("Adding one element in set using add() method")
foods.add("Sandwich")
print(foods)
print("Removing any one element ising remove() method")
foods.remove("Burger")
print(foods)
print("Removing last element using pop() method")
foods.pop()
print(foods)