friends = ("Nischal", "John", "Sujan", "Ujjwal", "Kushal", "Aayu", "John")
print(friends)
print("Data type of friends is", type(friends))
print("Total number of John names")
print(friends.count("John"))
print(friends.index("Ujjwal"))