subject = ["DL", "C", "IIT", "Math", "Physics"]
print(subject)
print("Removing one element")
subject.remove("Math")
print(subject)
print("Adding one element")
subject.append("Math")
print(subject)
print("Removing last element")
math = subject.pop()
print(subject)
print(math)
subject.pop()
print(subject)